### ISSUE TITLE
No error checking on adding user from admin side

### ISSUE THREAD

**Issue by Chaitanya31612** [shelcia/CRM#13]
![Screenshot (103)](https://user-images.githubusercontent.com/54992097/101519685-7b8c9880-39a9-11eb-9bf7-0a8e145d6773.png)
![Screenshot (104)](https://user-images.githubusercontent.com/54992097/101519698-7f201f80-39a9-11eb-8422-e889b0852b63.png)

I clicked on add and without filling all details I clicked on 'Add User' but in spite of getting an error message indicating error I got 'Successfully User Added'.

**If approved, I'd like to work on this issue.**

**Comment by shelcia** [comment]
Yes go ahead

**Comment by Chaitanya31612** [comment]
@shelcia I've made a pull request for this issue, please review it.
