### ISSUE TITLE
Use of sessionStorage instead of localStorage throughout the app.

### ISSUE THREAD

**Issue by Chaitanya31612** [shelcia/CRM#16]
The benefit of using this will be that the page session will last as long as the browser is open, and survives over page reloads and restores and sessionStorage is similar to localStorage but the difference is that while data in localStorage doesn't expire, data in sessionStorage is cleared when the page session ends. So it can be implemented.

**Comment by Chaitanya31612** [comment]
@shelcia I'd like to work on it once approved.

**Comment by Chaitanya31612** [comment]
@shelcia can you review this issue and tell whether I can work on this or not. This will eliminate the need of this "When users closes the active tab clear all local storage data #6".

**Comment by shelcia** [comment]
yeah that could be done instead
