### ISSUE TITLE
Add Documentation for users to understand

### ISSUE THREAD

**Issue by shelcia** [shelcia/CRM#8]

**Comment by DARK-art108** [comment]
can i work on this issue? Please assign

**Comment by DARK-art108** [comment]
@shelcia can you provide a more details that what things I need to add in the readme

**Comment by shelcia** [comment]
> @shelcia can you provide a more details that what things I need to add in the readme

Talk about the work flow and all authorisation rules

**Comment by Chaitanya31612** [comment]
If this issue is open I'd like to work on it. @shelcia please assign if it is available.
