### ISSUE TITLE
Code of Conduct and Readme Updation

### ISSUE THREAD

**Issue by Tejas1510** [shelcia/CRM#9]
The project lacks Code of Conduct and Contributing Guidelines which I think so are very important for an open-source project
So @shelcia can I work on this
Also, I would like to decorate the Readme so as to make it more attractive and beginners would find it easy to contribute

**Comment by Kerveyfelix** [comment]
Can I work on this issue?

**Comment by shelcia** [comment]
I would like to pull request from one of you guys. Decide who's gonna make that one

**Comment by Tejas1510** [comment]
@shelcia i have already made a PR https://github.com/shelcia/CRM/pull/11

**Comment by shelcia** [comment]
Also the other person made PR

**Comment by Tejas1510** [comment]
@shelcia It is true that another person has made the PR but the issue was generated by me and I was assigned it first
And according to the rules, we have first come first serve
So I think so you should merge my PR
Else depend on you
Thank you
